# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - cd cli && go mod tidy
#     # you may remove this if you don't need go generate
#     - cd cli && go generate ./...
before:
  hooks:
    - ./cli/scripts/completions.sh
    - ./cli/scripts/manpages.sh

monorepo:
  tag_prefix: infisical-cli/
  dir: cli

builds:
  - id: darwin-build
    binary: infisical
    ldflags:
      - -X github.com/Infisical/infisical-merge/packages/util.CLI_VERSION={{ .Version }}
      - -X github.com/Infisical/infisical-merge/packages/telemetry.POSTHOG_API_KEY_FOR_CLI={{ .Env.POSTHOG_API_KEY_FOR_CLI }}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    ignore:
      - goos: darwin
        goarch: "386"
    dir: ./cli

  - id: all-other-builds
    env:
      - CGO_ENABLED=0
    binary: infisical
    ldflags:
      - -X github.com/Infisical/infisical-merge/packages/util.CLI_VERSION={{ .Version }}
    flags:
      - -trimpath
    goos:
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: "386"
      - goos: freebsd
        goarch: "386"
    dir: ./cli

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - ../README*
      - ../LICENSE*
      - ../manpages/*
      - ../completions/*

release:
  replace_existing_draft: true
  mode: "replace"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-devel"

nfpms:
  - id: infisical
    package_name: infisical
    builds:
      - all-other-builds
    vendor: Infisical, Inc
    homepage: https://infisical.com/
    maintainer: Infisical, Inc
    description: The offical Infisical CLI
    license: MIT
    formats:
      - rpm
      - deb
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./completions/infisical.bash
        dst: /etc/bash_completion.d/infisical
      - src: ./completions/infisical.fish
        dst: /usr/share/fish/vendor_completions.d/infisical.fish
      - src: ./completions/infisical.zsh
        dst: /usr/share/zsh/site-functions/_infisical
      - src: ./manpages/infisical.1.gz
        dst: /usr/share/man/man1/infisical.1.gz
